name: flutter_dotenv
version: 5.1.0
description: Easily configure any flutter application with global variables using a `.env` file.
homepage: https://github.com/java-james/flutter_dotenv
environment:
  sdk: ">=2.12.0-0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
